// packages/db/lib/login-otp-whatsapp-notification.ts
//
// Shared, framework-agnostic WhatsApp delivery for the LOGIN_OTP
// authentication event — the Buyer (apps/web) and Supplier (apps/supplier)
// portal "Send OTP on WhatsApp" primary login flow.
//
// ARCHITECTURAL BOUNDARY (do not blur):
//   - This module NEVER generates, hashes, persists, or verifies an OTP. It
//     receives an ALREADY-GENERATED plaintext OTP (from the existing
//     apps/web/lib/otp-service `issueOtpChallenge()`/`OtpChallenge` model)
//     and is responsible ONLY for: policy check -> Meta WhatsApp Cloud API
//     send -> delivery log -> result. OTP lifecycle (expiry, attempts,
//     single-use, resend cooldown) remains entirely owned by
//     apps/web/lib/otp-service/challenge.ts.
//   - This is a NARROWLY SCOPED authentication-OTP send operation, not a
//     generic/arbitrary WhatsApp-message API — it always sends exactly the
//     `buildohub_login_otp` AUTHENTICATION-category template with exactly
//     one OTP value, never arbitrary text/components.
//
// WHY THIS LIVES HERE (packages/db) RATHER THAN apps/api:
// apps/web and apps/supplier are separate Next.js deployables with their own
// direct Prisma access — neither can import apps/api's NestJS
// NotificationEngineService/WhatsappNotificationService (NestJS-only, not a
// plain importable module). Mirrors the EXACT existing pattern already
// established for this exact problem — see
// packages/db/lib/customer-order-status-notification.ts's doc comment for
// the full rationale. Both apps call this same function directly, so there
// is exactly one send path, one dedupe mechanism, one policy evaluation,
// and one Meta transport for WhatsApp login OTP.
//
// Event type: LOGIN_OTP (channel: WHATSAPP) — see
// apps/api/src/notification-engine/notification-event-types.ts
// AUTHENTICATION_EVENT_TYPES and packages/db/scripts/seed-notification-templates.js
// for the NotificationEventPolicy registry row (templateName
// "buildohub_login_otp", metaTemplateId "1454146059894282", APPROVED,
// language "en" — verified live via the Meta Graph API on 2026-10-08).
//
// AUTHENTICATION EVENTS ALWAYS BYPASS BUSINESS NOTIFICATION CONTROLS: unlike
// evaluatePolicy() in customer-order-status-notification.ts (which DOES
// check NotificationGlobalSettings.whatsappBusinessEnabled and
// NotificationPreference.whatsappEnabled), this module's policy check
// deliberately NEVER consults either — login OTP must never be silently
// blocked by a business WhatsApp kill-switch or a user's business-alert
// opt-out preference (see notification-event-types.ts's
// MANDATORY_EVENT_TYPES / isMandatoryEventType, whose intent this mirrors
// at the code level rather than via a runtime flag, so it can never be
// accidentally defeated by a future admin-configurable toggle on this
// specific send path).
//
// Never throws — every failure (DB error, Meta error, missing config) is
// returned as a structured result. The CALLER (apps/web/lib/otp-service's
// delivery orchestration) decides what to tell the user and must never
// claim delivery succeeded unless `success: true` is returned here.

const EVENT_TYPE = "LOGIN_OTP";
const CHANNEL = "WHATSAPP";

/** The pre-created Meta AUTHENTICATION-category template this module always sends. */
export const LOGIN_OTP_TEMPLATE_NAME = "buildohub_login_otp";

export type LoginOtpWhatsAppPrismaClient = {
  notificationEventPolicy: { findUnique: (args: any) => Promise<any> };
  notificationEvent: {
    findUnique: (args: any) => Promise<any>;
    create: (args: any) => Promise<any>;
    update: (args: any) => Promise<any>;
  };
  whatsAppMessageLog: {
    create: (args: any) => Promise<any>;
    update: (args: any) => Promise<any>;
  };
};

export type NotifyLoginOtpWhatsAppParams = {
  /** The OtpChallenge.id this send corresponds to — used as the dedupe key so a
   * retried HTTP request can never double-send for the SAME challenge, while a
   * legitimate resend (which always creates a NEW challenge row, per the
   * existing issueOtpChallenge() invalidate-and-reissue lifecycle) always gets
   * a fresh, distinct dedupe key. See challenge.ts's invalidation behaviour —
   * this module relies on that guarantee rather than re-implementing it. */
  challengeId: string;
  /** E.164 WhatsApp-capable number to deliver to — already resolved by the
   * caller using the existing whatsappNumber -> phone convention and the
   * existing phone-normalization utilities. This module does not normalize,
   * validate, or otherwise interpret the phone number. */
  phone: string;
  /** Plaintext OTP, exactly as generated by issueOtpChallenge(). Never logged here. */
  otp: string;
};

export type NotifyLoginOtpWhatsAppResult =
  | { success: true; externalId: string }
  | { success: false; reason: string };

/** live | dry-run | off — mirrors WhatsAppEngineConfigService.getMode()'s contract exactly. */
export type LoginOtpWhatsAppMode = "live" | "dry-run" | "off";

/**
 * Reads NOTIFICATION_ENGINE_WHATSAPP_MODE — the SAME env var name already
 * used by apps/api's WhatsAppEngineConfigService.getMode() and by
 * customer-order-status-notification.ts. Never a second/renamed env var.
 */
export function getLoginOtpWhatsAppMode(): LoginOtpWhatsAppMode {
  const raw = (process.env.NOTIFICATION_ENGINE_WHATSAPP_MODE || "dry-run").toLowerCase();
  if (raw === "live" || raw === "off") return raw;
  return "dry-run";
}

/** Same env var names as WhatsAppEngineConfigService / customer-order-status-notification.ts — never duplicated/renamed. */
function getPhoneNumberId(): string | undefined {
  return process.env.WHATSAPP_PHONE_NUMBER_ID;
}

function getAccessToken(): string | undefined {
  return process.env.WHATSAPP_ACCESS_TOKEN;
}

/**
 * CONFIRMED: the live, APPROVED `buildohub_login_otp` template's language
 * is "en" (fetched via the Meta Graph API on 2026-10-08) — matches this
 * function's default exactly, no correction needed. Kept as a SEPARATE env
 * var from the business-template default "en_US"
 * (WHATSAPP_TEMPLATE_LANGUAGE) so changing this can never affect any
 * existing business template's language code.
 */
function getLoginOtpTemplateLanguage(): string {
  return process.env.WHATSAPP_LOGIN_OTP_TEMPLATE_LANGUAGE || "en";
}

function getGraphApiVersion(): string {
  return process.env.WHATSAPP_GRAPH_API_VERSION || "v20.0";
}

function getEndpoint(): string {
  return `https://graph.facebook.com/${getGraphApiVersion()}/${getPhoneNumberId()}/messages`;
}

type MetaGraphErrorBody = {
  error?: { message?: string; code?: number; error_subcode?: number };
};

function maskPhone(phone: string): string {
  if (phone.length <= 4) return "***";
  return `${phone.slice(0, 4)}***${phone.slice(-2)}`;
}

function formatMetaError(status: number, body: MetaGraphErrorBody): string {
  const err = body.error;
  if (!err) return `Meta Cloud API error (HTTP ${status})`;
  return `Meta Cloud API error (HTTP ${status}, code=${err.code ?? "n/a"}, subcode=${err.error_subcode ?? "n/a"}): ${err.message ?? "unknown"}`;
}

/**
 * Policy gate for LOGIN_OTP/WHATSAPP. Checks ONLY:
 *   1. The NotificationEventPolicy row exists and is enabled (Admin can
 *      still disable the LOGIN_OTP/WHATSAPP template entirely if e.g. the
 *      Meta template is pulled/rejected — this is the one intentional
 *      "off switch", not a business-preference toggle).
 *   2. Dedupe — a NotificationEvent with this exact dedupeKey has not
 *      already been created (guards a retried HTTP request from
 *      double-sending for the SAME OtpChallenge).
 *
 * Deliberately DOES NOT check NotificationGlobalSettings.whatsappBusinessEnabled
 * or NotificationPreference.whatsappEnabled — see this file's top doc
 * comment for why authentication sends must never be subject to business
 * kill-switches/opt-outs.
 */
async function evaluateLoginOtpPolicy(
  prisma: LoginOtpWhatsAppPrismaClient,
  dedupeKey: string
): Promise<{ allowed: true; templateName: string } | { allowed: false; reason: string }> {
  const policy = await prisma.notificationEventPolicy.findUnique({
    where: { eventType_channel: { eventType: EVENT_TYPE, channel: CHANNEL } },
  });

  if (!policy) {
    return { allowed: false, reason: "TEMPLATE_NOT_FOUND" };
  }
  if (!policy.enabled) {
    return { allowed: false, reason: "TEMPLATE_DISABLED" };
  }

  const existing = await prisma.notificationEvent.findUnique({ where: { dedupeKey } });
  if (existing) {
    return { allowed: false, reason: "DUPLICATE_DEDUPE_KEY" };
  }

  return { allowed: true, templateName: policy.templateName };
}

/**
 * Sends the `buildohub_login_otp` AUTHENTICATION-category template via the
 * Meta WhatsApp Cloud API, through the existing Notification Engine tables
 * (NotificationEventPolicy, NotificationEvent, WhatsAppMessageLog) — same
 * live/dry-run/off branching and WhatsAppMessageLog bookkeeping as every
 * other Meta send in this repo.
 *
 * Never throws. Returns `{ success: false, reason }` for every failure mode
 * (policy denial, missing config, Meta error, network error) — the caller
 * MUST treat any non-success result as "do not tell the user WhatsApp OTP
 * was sent".
 */
export async function notifyLoginOtpWhatsApp(
  prisma: LoginOtpWhatsAppPrismaClient,
  params: NotifyLoginOtpWhatsAppParams,
  onLog: (message: string) => void = () => undefined
): Promise<NotifyLoginOtpWhatsAppResult> {
  const { challengeId, phone, otp } = params;
  // Per-challenge dedupe key — NOT per-user/per-identifier, so a legitimate
  // resend (new challengeId after the old one is invalidated) is never
  // suppressed, while a retried HTTP request for the SAME challenge can
  // never double-send. See this file's top doc comment.
  const dedupeKey = `${EVENT_TYPE}:${challengeId}`;

  try {
    const decision = await evaluateLoginOtpPolicy(prisma, dedupeKey);

    if (!decision.allowed) {
      onLog(`LOGIN_OTP WhatsApp send suppressed for challenge=${challengeId}: reason=${decision.reason}`);
      return { success: false, reason: decision.reason };
    }

    const event = await prisma.notificationEvent.create({
      data: {
        eventType: EVENT_TYPE,
        recipientId: challengeId, // No resolved userId is guaranteed to exist yet (pre-login identifier) — the challenge IS the stable per-send identity.
        recipientType: "user",
        entityType: "OtpChallenge",
        entityId: challengeId,
        channel: CHANNEL,
        dedupeKey,
        payload: { challengeId },
        status: "created",
      },
    });

    const sendResult = await sendLoginOtpTemplateViaMeta(prisma, phone, decision.templateName, otp, onLog);

    await prisma.notificationEvent.update({
      where: { id: event.id },
      data: { status: sendResult.success ? "sent" : "failed" },
    });

    if (!sendResult.success) {
      return { success: false, reason: sendResult.error ?? "WHATSAPP_SEND_FAILED" };
    }
    return { success: true, externalId: sendResult.externalId ?? "" };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    onLog(`LOGIN_OTP WhatsApp send failed unexpectedly for challenge=${challengeId}: ${message}`);
    return { success: false, reason: "INTERNAL_ERROR" };
  }
}

/**
 * Low-level Meta Cloud API template send for buildohub_login_otp — body
 * (OTP) + button (OTP) components, never a free-form/arbitrary message.
 * Mirrors the existing live/dry-run/off branching and WhatsAppMessageLog
 * bookkeeping used by every other Meta send in this repo (see
 * customer-order-status-notification.ts's sendTemplateViaMeta). The
 * plaintext OTP is never logged — only delivery status/errors.
 *
 * Component structure CONFIRMED against the live, APPROVED
 * `buildohub_login_otp` template (fetched via the Meta Graph API
 * GET /{WABA_ID}/message_templates?name=buildohub_login_otp on 2026-10-08):
 * exactly 1 BODY variable ({{1}}=OTP) and one BUTTONS entry of type "URL"
 * ("Copy code", Meta's COPY_CODE-via-URL-button mechanism) whose dynamic
 * URL segment also carries the OTP as its one parameter. This is sent as
 * `{ type: "button", sub_type: "url", index: 0, parameters: [{ type: "text",
 * text: otp }] }` below — the standard Cloud API shape for a template's
 * dynamic URL button — identical to the shape already proven in production
 * by apps/api/src/whatsapp/whatsapp-auth.service.ts's
 * supplier_otp_verification AUTHENTICATION send. No payload change was
 * required after verification.
 */
async function sendLoginOtpTemplateViaMeta(
  prisma: LoginOtpWhatsAppPrismaClient,
  phone: string,
  templateName: string,
  otp: string,
  log: (message: string) => void
): Promise<{ success: boolean; externalId?: string; error?: string }> {
  const mode = getLoginOtpWhatsAppMode();

  const logRow = await prisma.whatsAppMessageLog.create({
    data: {
      phoneNumber: phone,
      templateName,
      direction: "outbound",
      status: "queued",
      // Never the plaintext OTP — observability only records that a send
      // was attempted, never the code itself.
      parameters: ["[REDACTED_OTP]"],
      mode,
    },
  });

  if (mode === "off") {
    await prisma.whatsAppMessageLog.update({
      where: { id: logRow.id },
      data: { status: "failed", errorDetails: "DISABLED_BY_CHANNEL" },
    });
    return { success: false, error: "DISABLED_BY_CHANNEL" };
  }

  if (mode === "dry-run") {
    const mockMessageId = `mock-wa-${logRow.id}`;
    await prisma.whatsAppMessageLog.update({
      where: { id: logRow.id },
      data: { status: "sent", metaMessageId: mockMessageId },
    });
    log(`[dry-run] Simulated LOGIN_OTP WhatsApp send template=${templateName} to=${maskPhone(phone)} mockMessageId=${mockMessageId}`);
    return { success: true, externalId: mockMessageId };
  }

  // mode === "live"
  try {
    const phoneNumberId = getPhoneNumberId();
    const accessToken = getAccessToken();
    if (!phoneNumberId || !accessToken) {
      const errorDetails = "WHATSAPP_PHONE_NUMBER_ID / WHATSAPP_ACCESS_TOKEN not configured";
      await prisma.whatsAppMessageLog.update({ where: { id: logRow.id }, data: { status: "failed", errorDetails } });
      return { success: false, error: errorDetails };
    }

    const payload = {
      messaging_product: "whatsapp",
      recipient_type: "individual",
      to: phone,
      type: "template",
      template: {
        name: templateName,
        language: { code: getLoginOtpTemplateLanguage() },
        components: [
          { type: "body", parameters: [{ type: "text", text: otp }] },
          { type: "button", sub_type: "url", index: 0, parameters: [{ type: "text", text: otp }] },
        ],
      },
    };

    const response = await fetch(getEndpoint(), {
      method: "POST",
      headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });

    if (response.ok) {
      const body = (await response.json()) as { messages?: Array<{ id: string }> };
      const metaMessageId = body.messages?.[0]?.id;
      await prisma.whatsAppMessageLog.update({ where: { id: logRow.id }, data: { status: "sent", metaMessageId } });
      return { success: true, externalId: metaMessageId };
    }

    const errorBody = (await response.json().catch(() => ({}))) as MetaGraphErrorBody;
    const errorDetails = formatMetaError(response.status, errorBody);
    log(`[meta-whatsapp] LOGIN_OTP send to ${maskPhone(phone)} failed: ${errorDetails}`);
    await prisma.whatsAppMessageLog.update({ where: { id: logRow.id }, data: { status: "failed", errorDetails } });
    return { success: false, error: errorDetails };
  } catch (error) {
    const errorDetails = error instanceof Error ? error.message : "Unknown WhatsApp send error";
    log(`[meta-whatsapp] Network error sending LOGIN_OTP to ${maskPhone(phone)}: ${errorDetails}`);
    await prisma.whatsAppMessageLog
      .update({ where: { id: logRow.id }, data: { status: "failed", errorDetails } })
      .catch(() => undefined);
    return { success: false, error: errorDetails };
  }
}
