-- AlterEnum
ALTER TYPE "NotificationTemplateType" ADD VALUE 'AGGREGATION_OPT_IN_CONFIRMED';
ALTER TYPE "NotificationTemplateType" ADD VALUE 'AGGREGATION_TIER_IMPROVED';
ALTER TYPE "NotificationTemplateType" ADD VALUE 'AGGREGATION_WINDOW_CLOSING_SOON';
ALTER TYPE "NotificationTemplateType" ADD VALUE 'AGGREGATION_POOL_LOCKED';
ALTER TYPE "NotificationTemplateType" ADD VALUE 'AGGREGATION_OPT_OUT_CONFIRMED';
